ROOT_FOLDER :  "./"

# Dataset related parameters
DATASET_FOLDER : "./data/"
VIT_FOLDER : "./data/VITF/"

# Image Model Training Parameters
IMAGE_FEATURE_EXTRACTOR : "VIT"
EPOCHS: 20
BATCH_SIZE: 10
LEARNING_RATE: 0.001 #1e-4
LOG_INTERVAL: 100
NUM_WORKERS: 2 # only GPU option
PIN_MEMORY: True # only GPU option



key1: "This is a "
key2: "concatenated string."


