ROOT_FOLDER :  "./"

# Dataset related parameters
DATASET_FOLDER : "./data/"
VIT_FOLDER : "./data/VITF/"
MFCC_FOLDER: "./data/MFCCF/"
PICKLE_FOLDER: "./saved_pickles/"
TRANSCRIPTS_FOLDER: "./data/transcripts/"

# Image Model Training Parameters
UNIMODAL_FEATURE_EXTRACTOR : "BERT"
EPOCHS: 20
BATCH_SIZE: 10
LEARNING_RATE: 0.0001 #1e-4  
LOG_INTERVAL: 1000 # print training results after how many batches
NUM_WORKERS: 2 # only GPU option
PIN_MEMORY: True # only GPU option


AUDIO_FEATURE_EXTRACTOR: "MFCC"
VIDEO_FEATURE_EXTRACTOR: "VIT"
TEXT_FEATURE_EXTRACTOR: "BERT"

MODALILTIES: "AUD"

# Modality-specific hyperparameters
TEXT_HIDDEN_LAYERS: 1 # total layers = TEXT_HIDDEN_LAYERS + 2 (first and last fixed)
AUD_HIDDEN_LAYERS: 1
VID_HIDDEN_LAYERS: 1


USE_SCHEDULER: 1